---
platform: linux
image: docker:///bosh/vcloud-cpi-release
tags: ["vcloud"]
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bosh-concourse-ci
  - name: bats
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
params:
  base_os:              replace-me
  BAT_NETWORKING:       replace-me
  VCLOUD_VLAN:          replace-me
  NETWORK_CIDR:         replace-me
  NETWORK_GATEWAY:      replace-me
  BATS_DIRECTOR_IP:     replace-me
  BATS_STEMCELL_NAME:   replace-me
  BATS_IP1:             replace-me
  BATS_IP2:             replace-me
  BATS_RESERVED_RANGE1: replace-me
  BATS_RESERVED_RANGE2: replace-me
  BATS_STATIC_RANGE:    replace-me
