---
platform: linux
image: docker:///bosh/vcloud-cpi-release
inputs:
  - name: deploy             # --- task that updated the deployment state
  - name: bosh-cpi-release   # --- location of task script to run
run:
  path: bosh-cpi-release/ci/tasks/save-deployment.sh
params:
  base_os:              replace-me
  network_type_to_test: replace-me
