---
ruby_vcloud_cpi/ruby-1.9.3-p545.tar.gz:
  object_id: c566b935-f287-4c46-8bda-5a85c3369246
  sha: !binary |-
    MDM0NTUzNjQ3NDA5MTRlOGQyZGZkNjQyMWY2ODFiM2ZiNjhhNDMxMw==
  size: 12582277
ruby_vcloud_cpi/yaml-0.1.5.tar.gz:
  object_id: 3cac255b-88e0-4f9f-ac09-80a5e0c8d65d
  sha: !binary |-
    OGI3OGNiOWY3NTljN2Q4MGRiOGE3MzI4YzBlYmVjZmUzNGZkZTczNw==
  size: 504897
ruby_vcloud_cpi/rubygems-2.1.11.tgz:
  object_id: 6a67e4cc-0188-47de-a372-e9a9e52e9cfb
  sha: !binary |-
    Y2EzMDMzNDMyY2FlMjhkZWI3Y2VkNzljZGEyNzFjYjI5MmI3MGU1OQ==
  size: 367166