---
groups:
  - name: bosh-vcloud-cpi-release
    jobs:
      - create-jumpbox-v5.5
      - create-jumpbox-v5.6
      - build-candidate
      - lifecycle-v5.5
      - lifecycle-v5.6
      - promote-candidate

jobs:
  - name: create-jumpbox-v5.5
    plan:
      - aggregate:
        - {trigger: false,  get: bosh-cpi-release, tags: ["vcloud-v5.5"]}

      - task: sleep
        file: bosh-cpi-release/ci/tasks/create-jumpbox.yml
        tags: ["vcloud-v5.5"]

  - name: create-jumpbox-v5.6
    plan:
      - aggregate:
        - {trigger: false,  get: bosh-cpi-release, tags: ["vcloud-v5.6"]}

      - task: sleep
        file: bosh-cpi-release/ci/tasks/create-jumpbox.yml
        tags: ["vcloud-v5.6"]

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-release/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: candidate/.*\.tgz}

  - name: lifecycle-v5.5
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts, tags: ["vcloud-v5.5"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release, tags: ["vcloud-v5.5"]}
        - {trigger: false,                            get: stemcell, resource: vcloud-ubuntu-stemcell, tags: ["vcloud-v5.5"]}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
        tags: ["vcloud-v5.5"]
        params:
          VCLOUD_HOST:     {{VCLOUD_HOST_V5_5}}
          VCLOUD_USER:     {{VCLOUD_USER_V5_5}}
          VCLOUD_PASSWORD: {{VCLOUD_PASSWORD_V5_5}}
          VCLOUD_VLAN:     {{VCLOUD_VLAN}}
          VCLOUD_ORG:      {{VCLOUD_ORG_V5_5}}
          VCLOUD_VDC:      {{VCLOUD_VDC_V5_5}}
          NETWORK_NETMASK: {{NETWORK_NETMASK}}
          NETWORK_DNS:     {{NETWORK_DNS}}
          NETWORK_GATEWAY: {{NETWORK_GATEWAY}}
          LIFECYCLE_IP1:   {{LIFECYCLE_IP1}}
          LIFECYCLE_IP2:   {{LIFECYCLE_IP2}}

  - name: lifecycle-v5.6
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts, tags: ["vcloud-v5.6"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release, tags: ["vcloud-v5.6"]}
        - {trigger: false,                            get: stemcell, resource: vcloud-ubuntu-stemcell, tags: ["vcloud-v5.6"]}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
        tags: ["vcloud-v5.6"]
        params:
          VCLOUD_HOST:     {{VCLOUD_HOST_V5_6}}
          VCLOUD_USER:     {{VCLOUD_USER_V5_6}}
          VCLOUD_PASSWORD: {{VCLOUD_PASSWORD_V5_6}}
          VCLOUD_VLAN:     {{VCLOUD_VLAN}}
          VCLOUD_ORG:      {{VCLOUD_ORG_V5_6}}
          VCLOUD_VDC:      {{VCLOUD_VDC_V5_6}}
          NETWORK_NETMASK: {{NETWORK_NETMASK}}
          NETWORK_DNS:     {{NETWORK_DNS}}
          NETWORK_GATEWAY: {{NETWORK_GATEWAY}}
          LIFECYCLE_IP1:   {{LIFECYCLE_IP1}}
          LIFECYCLE_IP2:   {{LIFECYCLE_IP2}}

  - name: promote-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, passed: [lifecycle-v5.5], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [lifecycle-v5.5], get: bosh-cpi-release}
        - {trigger: false, get: release-version-semver, params: {bump: major}}

      - task: promote
        file: bosh-cpi-release/ci/tasks/promote-candidate.yml
        params:
          aws_access_key_id: {{s3_vcloud_cpi_blobwriter_access_key}}
          aws_secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

      - put: bosh-cpi-release
        params: {repository: promote/bosh-cpi-release, rebase: true, tag_prefix: "v", tag: promote/integer_version}

      - put: release-version-semver
        params: {file: release-version-semver/number}

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-vcloud-cpi\.tgz
      bucket: bosh-vcloud-cpi-release
      region_name: us-east-1
      access_key_id:     {{s3_vcloud_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

  - name: bosh-cpi-release
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-vcloud-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-vcloud-cpi-release}}

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            bosh-vcloud-cpi-release
      access_key_id:     {{s3_vcloud_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            bosh-vcloud-cpi-release
      access_key_id:     {{s3_vcloud_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

  - name: vcloud-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
