---
groups:
  - name: certify-vcloud
    jobs:
      - setup-director-ubuntu-v5.5
      - setup-director-ubuntu-v5.6
      - bats-ubuntu-v5.5
      - bats-ubuntu-v5.6

jobs:
  - name: setup-director-ubuntu-v5.5
    serial_groups: [vcloud-v5.5-serial-group]
    plan:
      - aggregate:
        - {trigger: true,  get: bosh-cpi-release, tags: ["vcloud-v5.5"]}
        - {trigger: true,  get: bosh-release, tags: ["vcloud-v5.5"]}
        - {trigger: true,  get: stemcell, resource: ubuntu-stemcell, tags: ["vcloud-v5.5"]}
        - {trigger: false, get: bosh-cpi-src, tags: ["vcloud-v5.5"]}
        - {trigger: false, get: director-state-file, resource: ubuntu-manual-director-state-file-v5-5, tags: ["vcloud-v5.5"]}
        - {trigger: false, get: bosh-init, tags: ["vcloud-v5.5"]}

      - task: deploy
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        tags: ["vcloud-v5.5"]
        config:
          params:
            base_os:              ubuntu
            network_type_to_test: manual
            VCLOUD_HOST:          {{VCLOUD_HOST_V5_5}}
            VCLOUD_USER:          {{VCLOUD_USER_V5_5}}
            VCLOUD_PASSWORD:      {{VCLOUD_PASSWORD_V5_5}}
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            VCLOUD_ORG:           {{VCLOUD_ORG_V5_5}}
            VCLOUD_VDC:           {{VCLOUD_VDC_V5_5}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
        ensure:
          put: ubuntu-manual-director-state-file-v5-5
          tags: ["vcloud-v5.5"]
          params: {from: deployment/ubuntu-manual-director-manifest-state.json}

  - name: setup-director-ubuntu-v5.6
    serial_groups: [vcloud-v5.6-serial-group]
    plan:
      - aggregate:
        - {trigger: true,  get: bosh-cpi-release, tags: ["vcloud-v5.6"]}
        - {trigger: true,  get: bosh-release, tags: ["vcloud-v5.6"]}
        - {trigger: true,  get: stemcell, resource: ubuntu-stemcell, tags: ["vcloud-v5.6"]}
        - {trigger: false, get: bosh-cpi-src, tags: ["vcloud-v5.6"]}
        - {trigger: false, get: director-state-file, resource: ubuntu-manual-director-state-file-v5-6, tags: ["vcloud-v5.6"]}
        - {trigger: false, get: bosh-init, tags: ["vcloud-v5.6"]}

      - task: deploy
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        tags: ["vcloud-v5.6"]
        config:
          params:
            base_os:              ubuntu
            network_type_to_test: manual
            VCLOUD_HOST:          {{VCLOUD_HOST_V5_6}}
            VCLOUD_USER:          {{VCLOUD_USER_V5_6}}
            VCLOUD_PASSWORD:      {{VCLOUD_PASSWORD_V5_6}}
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            VCLOUD_ORG:           {{VCLOUD_ORG_V5_6}}
            VCLOUD_VDC:           {{VCLOUD_VDC_V5_6}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
        ensure:
          put: ubuntu-manual-director-state-file-v5-6
          tags: ["vcloud-v5.6"]
          params: {from: deployment/ubuntu-manual-director-manifest-state.json}

  - name: bats-ubuntu-v5.5
    serial_groups: [vcloud-v5.5-serial-group]
    plan:
      - aggregate:
        - {trigger: true,  get: bosh-cpi-release, passed: [setup-director-ubuntu-v5.5], tags: ["vcloud-v5.5"]}
        - {trigger: true,  get: bosh-release, passed: [setup-director-ubuntu-v5.5], tags: ["vcloud-v5.5"]}
        - {trigger: true,  get: stemcell, passed: [setup-director-ubuntu-v5.5], resource: ubuntu-stemcell, tags: ["vcloud-v5.5"]}
        - {trigger: false, get: bosh-cpi-src, tags: ["vcloud-v5.5"]}
        - {trigger: false, get: bats, tags: ["vcloud-v5.5"]}

      - task: test
        file: bosh-cpi-src/ci/tasks/run-bats.yml
        tags: ["vcloud-v5.5"]
        config:
          params:
            base_os:              ubuntu
            BAT_NETWORKING:       manual
            BATS_STEMCELL_NAME:   bosh-vcloud-esxi-ubuntu-trusty-go_agent
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
            BATS_IP1:             {{BATS_IP1_ubuntu}}
            BATS_IP2:             {{BATS_IP2_ubuntu}}
            BATS_RESERVED_RANGE1: {{BATS_RESERVED_RANGE1_ubuntu}}
            BATS_RESERVED_RANGE2: {{BATS_RESERVED_RANGE2_ubuntu}}
            BATS_STATIC_RANGE:    {{BATS_STATIC_RANGE_ubuntu}}

  - name: bats-ubuntu-v5.6
    serial_groups: [vcloud-v5.6-serial-group]
    plan:
      - aggregate:
        - {trigger: true,  get: bosh-cpi-release, passed: [setup-director-ubuntu-v5.6], tags: ["vcloud-v5.6"]}
        - {trigger: true,  get: bosh-release, passed: [setup-director-ubuntu-v5.6], tags: ["vcloud-v5.6"]}
        - {trigger: true,  get: stemcell, passed: [setup-director-ubuntu-v5.6], resource: ubuntu-stemcell, tags: ["vcloud-v5.6"]}
        - {trigger: false, get: bosh-cpi-src, tags: ["vcloud-v5.6"]}
        - {trigger: false, get: bats, tags: ["vcloud-v5.6"]}

      - task: test
        file: bosh-cpi-src/ci/tasks/run-bats.yml
        tags: ["vcloud-v5.6"]
        config:
          params:
            base_os:              ubuntu
            BAT_NETWORKING:       manual
            BATS_STEMCELL_NAME:   bosh-vcloud-esxi-ubuntu-trusty-go_agent
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
            BATS_IP1:             {{BATS_IP1_ubuntu}}
            BATS_IP2:             {{BATS_IP2_ubuntu}}
            BATS_RESERVED_RANGE1: {{BATS_RESERVED_RANGE1_ubuntu}}
            BATS_RESERVED_RANGE2: {{BATS_RESERVED_RANGE2_ubuntu}}
            BATS_STATIC_RANGE:    {{BATS_STATIC_RANGE_ubuntu}}

resources:
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-vcloud-cpi-release
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vcloud-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vcloud-esxi-ubuntu-trusty-go_agent

  - name: ubuntu-manual-director-state-file-v5-5
    type: s3
    source:
      bucket: bosh-vcloud-cpi-ubuntu-state-files-v5-5
      versioned_file: ubuntu-manual-director-manifest-state.json
      region_name: us-east-1
      access_key_id:     {{s3_vcloud_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

  - name: ubuntu-manual-director-state-file-v5-6
    type: s3
    source:
      bucket: bosh-vcloud-cpi-ubuntu-state-files-v5-6
      versioned_file: ubuntu-manual-director-manifest-state.json
      region_name: us-east-1
      access_key_id:     {{s3_vcloud_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: certification
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: receipt-.*\.json
      region_name: us-east-1
